### PR TITLE
External schemes fix

### PR DESCRIPTION
**Pull request by bwaresiak**
Task/Issue URL: https://app.asana.com/0/856498667320406/1161274873210818

**Description**:
Some external schemes are not working properly. Examples:
- App Store links.
- Custom External App schemes.

**Steps to test this PR**:

To test:
1. Check App Store/ iTunes links.
2. Check schemes: sms, message, mailto, phone.
3. Ensure general navigation around web works (http, https, ftp, ...).
4. Check iOS-specific ones: facetime, Maps URL.
5. Check some external (custom) schemes.

**Orientation Testing**:

* [x] Portrait
* [x] Landscape

**Device Testing**:

* [x] iPhone SE (1st Gen)
* [x] iPhone 8
* [x] iPhone X
* [x] iPad

**OS Testing**:

* [x] iOS 10
* [x] iOS 11
* [x] iOS 12
* [x] iOS 13

**Theme Testing**:

* [x] Light theme
* [x] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Review by brindy — APPROVED** [review]
LGTM!

**Comment by bwaresiak** [comment]
Thanks!

**Comment by MathPlayer** [comment]
This fix still does not work for me when using DuckDuckGo with https://lichess.org/ and their custom URL schema to open the links in their iOS app. Using Safari works.

**Comment by bwaresiak** [comment]
@MathPlayer Sorry to hear that. If you've encountered a problem please report an issue with steps to reproduce (do we need an account there, what is the exact flow that does not work, you can attach screens or video) so we can test it and look for solution. Thanks!

**Pull request merged**
