### PR TITLE
Allow remote autofill toggling for all users

### PR DESCRIPTION
**Pull request by graeme**
Task/Issue URL: https://app.asana.com/0/414235014887631/1204349262808609/f
Tech Design URL:
CC: @THISISDINOSAUR @amddg44 

**Description**:

This PR makes the autofill subfeature toggleable for all users. The will remain hidden unless toggled to `enabled` on the privacy config.

**Steps to test this PR**:
1. Check autofill features are invisible when not internal
2. Check autofill features are visible when internal
3. Become non-internal (reinstall app), mock privacy config response enabling autofill subfeatures using Charles / Proxyman (or similar) and check that they are visible.

For making sure the privacy-config is re-fetched after you make a change to your mocked response:
1. Make sure you increment the eTag in the response header each time you change it
2. Tweak the `AppConfigurationFetch.Constants.minimumConfigurationRefreshInterval` as it’s set to 30 mins by default.
3. (You might need to relaunch the app to refresh the app’s UI state.)

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `’`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [x] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [x] iPhone 14 Pro
* [x] iPad

**OS Testing**:

* [x] iOS 14
* [ ] iOS 15
* [x] iOS 16

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

—
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by THISISDINOSAUR** [comment]
Edit: we discussed on MM, it's unrelated

I have no idea if it's related, but when trying to test email (right after logging in) I hit this assertion failure in BSK.APIRequest
private func assertUserAgentIsPresent() {
        guard request.allHTTPHeaderFields?[HTTPHeaderField.userAgent] != nil else {
            assertionFailure("A user agent must be included in the request's HTTP header fields.")
            return
        }
    }

**Review by THISISDINOSAUR — COMMENTED** [review]
I can't get it to work when setting to be enabled to everyone, it's possible I made a mistake in the file I'm mapping to locally. 

Here's the file I'm mapping to locally, do you have one I can compare it to?
[ios-config 2.txt](https://github.com/duckduckgo/iOS/files/11180048/ios-config.2.txt)

**Comment by THISISDINOSAUR** [comment]
I managed to get that working, but now I'm testing disabling the parent feature whilst the sub features are enabled and I'm pretty sure it's not using the right config and I can't find a way to get it to.

**Comment by graeme** [comment]
@THISISDINOSAUR Excuse the delay. A few things:
1. Make sure you increment the eTag in the response header each time you change it
2. Tweak the `AppConfigurationFetch.Constants.minimumConfigurationRefreshInterval` as it’s set to 30 mins by default.
3. You might need to relaunch the app to refresh the app’s UI state.

**Comment by THISISDINOSAUR** [comment]
I did #1 and #3, re 2 I reset the refresh time using the debug panel which I figure should have the same impact, but I guess not? Either way I'll try #2

**Comment by THISISDINOSAUR** [comment]
I tested a variety of things (e.g. sub features enabled but parent feature disabled, various mixes of sub features) and everything LGTM!

**Review by THISISDINOSAUR — APPROVED** [review]

**Pull request merged**
