### PR TITLE
don't extend edges under the top and bottom bars for the container view

### PR DESCRIPTION
**Pull request by brindy**
Reviewer: Mia
Asana: https://app.asana.com/0/414235014887631/416322909657029
CC:

**Description**:

The web view was hiding content expecting to be at the bottom of the page.  Solution was to not extend the container view under the top and bottom bars.

**Steps to test this PR**:
1. Go to donttrack.us - observe the "down" circle button at the bottom of the page.
2. Go to squarespace.com - after dismissing the cookie alert observe the "get started" button at the bottom of the page
3. Go to hugeinc.com - observe the text attached to the bottom of the screen, e.g. "Magenta\nRead our latest articles on design and technology."

###### Reviewer Checklist:
- [ ] **Ensure the PR solves the problem**
- [ ] **Review every line of code**
- [ ] **Ensure the PR does no harm by testing the changes thoroughly**
- [ ] **Get help if you're uncomfortable with any of the above!**
- [ ] Determine if there are any quick wins that improve the implementation

###### PR DRI Checklist:
- [ ] Get advice or leverage existing code
- [ ] Agree on technical approach with reviewer (if the changes are nuanced)
- [ ] Ensure that there is a testing strategy (and documented non-automated tests)
- [ ] Ensure there is a documented monitoring strategy (if necessary)
- [ ] Consider systems implications (Database connections, Grafana stats, CPU)

### CODE REVIEW

**Comment by subsymbolic** [comment]
This looks good but it seems to introduce a new problem. When I scroll so that the bars are hidden I can no longer see the top or the bottom of the page. I have to unhide the bar to see them.

In the image I can tug at the page to show the top, then it bounces behind the status bar.
screen shot 2017-09-07 at 17 33 28

**Comment by brindy** [comment]
Have had to set the constraints on the view manually so that the top of the webView matches the top of the progress bar. Ideally I think there should be another View in the story board which is placed correctly and then the web view is added to that, but I didn't want to duplicate that effort in both story boards (i.e. share extension).

**Comment by subsymbolic** [comment]
Getting closer, although there's a new issue now. When the bars are hidden I can no longer swipe down to get them back.

**Comment by brindy** [comment]
I'm going down a rabbit hole with this one! :)  Going to close this for now and come back to it later.

**Pull request closed without merging**
