### PR TITLE
Add support for email protection logout

### PR DESCRIPTION
**Pull request by alistairjcbrown**
Task/Issue URL: https://app.asana.com/0/0/1202050175851752/f
Tech Design URL:
CC:

**Description**:

~BSK PR: https://github.com/duckduckgo/BrowserServicesKit/pull/98~
~Before merging, there will need to be a new release of BSK and the development branch used in this PR swapped out~

Updates iOS browser to use new BSK version to support log out from the Email Protection web app. Supports post message back to the Email Protection web app whenever log out occurs.

**Steps to test this PR**:
1. Go to https://duckduckgo.com/email/settings and log in
   - Confirm that the device has email autofill **enabled**
2. A "Sign Out" button should be visible at the bottom of the Email Protection settings page
3. Click the "Sign Out" button -- you should be logged out of the settings page without needing to refresh the page
   - Confirm that the device has email autofill **disabled**

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPad

**OS Testing**:

* [ ] iOS 13
* [ ] iOS 14
* [ ] iOS 15

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Comment by bwaresiak** [comment]
@alistairjcbrown what's the context of this change and priority? Is this ready for review?

**Comment by alistairjcbrown** [comment]
@bwaresiak It's part of implementing sign out functionality for the Email Protection web app -- https://app.asana.com/0/1198915719297225/1201042398316742/f
The feature requires updating autofill, BSK and macOS and iOS -- so I'm trying to get all the PRs lined up. It's ready for review, but not ready to merge until we can cascade the releases from autofill, BSK and then up to here. I hope that makes sense!

**Review by samsymons — APPROVED** [review]
iOS PR looks good! 

A part of me wants to move the `webView.evaluateJavaScript("window.postMessage({ emailProtectionSignedOut: true }, window.origin);")` call up into BSK in order for it to be reused across platforms, but it's such a minor thing that I wouldn't worry too much about it here.

**Comment by samsymons** [comment]
@alistairjcbrown Is there anything left for us to do here, or can we merge?

**Comment by alistairjcbrown** [comment]
@samsymons Sorry for the delay, there's a wee cascade of dependency releases first -- I'm waiting on the autofill change to merge and release, so I can update the BSK branch (and merge and release), to update this branch with the latest BSK.

**Pull request merged**
