### PR TITLE
Using the $APP_ID variable on the WidgetExtension and OpenAction targets

### PR DESCRIPTION
**Pull request by gholias**
Task/Issue URL: https://github.com/duckduckgo/iOS/issues/713
Tech Design URL: N/A
CC: N/A

**Description**:

**Steps to test this PR**:
1.  Follow the steps to set up an external developer account from the repo readme - https://github.com/duckduckgo/iOS
2. You should be able to create an App Id that is unique to your developer account and run the project.

**Copy Testing**:

* [x] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape
* [x] N/A

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPad
* [x] N/A

**OS Testing**:

* [ ] iOS 11
* [ ] iOS 12
* [ ] iOS 13
* [x] iOS 14

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme
* [x] N/A
---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by brindy** [comment]
Thanks for this! It's been a busy couple of weeks so we're starting to pick these up now.

**Comment by brindy** [comment]
Hi @gholias - this certainly seems to work for DDG developers, so no problems/breakages there.  

The problem is we have a new managed entitlement in the app  (`com.apple.developer.web-browser`) which will not be available to external developers, see [DuckDuckGo.entitlements](https://github.com/duckduckgo/iOS/blob/develop/DuckDuckGo/DuckDuckGo.entitlements)

Do you have any thoughts on the best approach for managing that with external developers?

Thanks!

**Comment by gholias** [comment]
Hi @brindy - My idea to fix the entitlement problem would be having a script that uses Fastlane to generate the App Identifiers in the developer Apple Developer Account.
This is my idea for the script:
```
#!/usr/bin/env bash
# exit if a command fails
set -e

export FASTLANE_USER="-"
export FASTLANE_PASSWORD="-"
export FASTLANE_TEAM_ID="XXXXX"

export APP_ID="com.externaldeveloper.duckduckgo.mobile.ios"
export GROUP_ID_PREFIX="group.${APP_ID}"

declare -A IDS   

IDS["DuckDuckGo"]=$APP_ID
IDS["BookmarksTodayExtension"]="${APP_ID}.BookmarksTodayExtension"
IDS["QuickActionsTodayExtension"]="${APP_ID}.QuickActionsTodayExtension"
IDS["OpenAction"]="${APP_ID}.OpenAction2"
IDS["WidgetsExtension"]="${APP_ID}.Widgets"


for ID in "${!IDS[@]}"; do
    
    BUNDLE_ID="${IDS[$ID]}"
    APP_NAME="${ID}"

    echo "(i) Producing app $ID with bundleId $BUNDLE_ID and group $GROUP_ID_PREFIX"

    fastlane produce --app_identifier $BUNDLE_ID --app_name "$APP_NAME" --skip_itc
    fastlane produce enable_services --app-group --app_identifier $BUNDLE_ID
    fastlane produce associate_group --app_identifier $BUNDLE_ID $GROUP
done
```

The problem with that approach is that the developer will need to have Fastlane installed in their machine.
Also, I'm having some issues with xcode12 and automatic signing for the project. I will try to make it work if you think that is a viable approach to the problem.

What do you think?

**Comment by brindy** [comment]
Thanks @gholias - let me think on that.  In the meantime thanks for this PR!

**Pull request merged**
