### PR TITLE
allow tab reordering

### PR DESCRIPTION
**Pull request by brindy**
Task/Issue URL: https://app.asana.com/0/414709148257752/1152213134668529
Tech Design URL:
CC:

**Description**:

Allow tab reordering

**Steps to test this PR**:
1. Ensure tabs can be reordered and maintain the selection highlight

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Review by bwaresiak — COMMENTED** [review]
Nice! That feature is so useful! 

I've found two glitches:

1. When cell is moved back to its initial position it "jumps" a bit:

glitch-reorder-tab


2. When cell move results in scrolling of the collection view, cell view seem to be duplicated (at the end of the video):

glitch-reorder-tab2

**Comment by brindy** [comment]
Thanks @bwaresiak :) 

As you can see from the code I've not written much code beyond just basic implementation of delegate methods and letting the UICollectionView know it needs to do something so I think a lot of what you see is UICollectionView default behaviour. 

Is this "good enough" ?   Perfection being the enemy of good enough. :)  It's much better than what we have now (ie nothing) but not terrible... and there's a major overhaul on the horizon anyway hopefully.

**Comment by bwaresiak** [comment]
Considering we are likely to change that screen in the future anyway, I think this is good enough :)

**Review by bwaresiak — APPROVED** [review]

**Comment by brindy** [comment]
Thanks @bwaresiak

**Pull request merged**
