### PR TITLE
Autofill list view changes

### PR DESCRIPTION
**Pull request by amddg44**
Task/Issue URL: https://app.asana.com/0/0/1202808746542215/f
Tech Design URL:
CC:

**Description**:
Various UI detail updates including fixing items 2.1, 2.3, 4, 5.1 and 5.3. Also additional state handling for navigation bar buttons, dynamic height support added to cells + other views, full dark mode support, minor other UI tidy ups. 

Note that layout is targeting iPhone portrait only for now, will tackle landscape + iPad support in another PR  

**Steps to test this PR**:
1. Run through the various UI states and confirm everything matches design paying special attention to SearchController and navigation buttons
2. Also run through in dark mode 

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPad

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Comment by THISISDINOSAUR** [comment]
Nice re dark mode!

I'm seeing some strange jumping when navigating whilst searching, I think it's a regression, see video (you might need to download the video, viewing it browser didn't work for me):
https://user-images.githubusercontent.com/1093508/189210845-d90ad59a-32d4-4831-81eb-09e75a27793d.mp4


Not sure if the PR is supposed to address any of these, and since it's still all improvements I think it's fine to merge, but I noticed a few things:

- Pull down on search, the way the bar appears is very abrumpt in a way the bookmarks one isn't
- Should we have dynamic height (As opposed to truncating/whatever)? Might be worth checking with the design crew
- Logo still wrong for empty state?
IMG_0519

- When auth is disabled, the view controller just seems to get dismissed
https://user-images.githubusercontent.com/1093508/189210886-db50f8e2-3789-4173-91e1-126ecabe4e21.MP4

**Comment by THISISDINOSAUR** [comment]
Found another one
- If I delete all the logins there's an errant done button 
Simulator Screen Shot - iPhone 13 Pro - 2022-09-08 at 20 53 10

**Comment by amddg44** [comment]
> I'm seeing some strange jumping when navigating whilst searching, I think it's a regression, see video (you might need to download the video, viewing it browser didn't work for me): https://user-images.githubusercontent.com/1093508/189210845-d90ad59a-32d4-4831-81eb-09e75a27793d.mp4
> 

That video was really interesting esp as I'm not seeing that same behaviour at all - can you tell me what device + iOS version you were testing on? 

https://user-images.githubusercontent.com/91189922/189291460-5dd1ed79-9451-498b-8321-a31e2bd787c7.mov




> * Should we have dynamic height (As opposed to truncating/whatever)? Might be worth checking with the design crew

Checking re dynamic height :thumbsup:


> * Logo still wrong for empty state?

Logo is updated (In figma there is a note that icon is a placholder so didn't realise it was final)


> * When auth is disabled, the view controller just seems to get dismissed

Nice find - I hadn't touched any of that logic and I can't reproduce this on iPhone, it seems like an iPad only issue. Would it be best to tackle it as part of this PR or would it be better as part of the PR targeting iPad improvements? https://user-images.githubusercontent.com/91189922/189290442-a07205e6-d438-49d9-b915-9c80c35b4808.mov

**Comment by amddg44** [comment]
> Found another one
> 
> * If I delete all the logins there's an errant done button

Good catch, that's fixed 👍

**Comment by THISISDINOSAUR** [comment]
Re the auth issue, if it's just iPad I think that's fine to defer, I was just unable to see the interface for when auth is disabled

**Review by THISISDINOSAUR — APPROVED** [review]
Just tested with the changes, LGTM!

**Pull request merged**
