### PR TITLE
Prefer url to text and support news share

### PR DESCRIPTION
**Pull request by subsymbolic**
Task/Issue URL:
https://app.asana.com/0/inbox/361428290920650/707363199948632/710405791669018
https://app.asana.com/0/inbox/361428290920650/710279313504428/710405791669018

Tech Design URL: N/A

**Description**:
Adds News share support, allowing News to share pages with our app. Also prefers url to text shares.

**Steps to test this PR**:
1. Open the News app and share a story, ensure the url opens in our app
1. Open Brave and share a url, ensure the url (not the text) opens in our app

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Review by brindy — APPROVED** [review]
LGTM

optional - did you use that SO to determine that subquery? is it worth referencing back with a comment?

**Review by brindy — COMMENTED** [review]
Bug: 

Not sure what you think about this.

* Create a note in "Notes"
* Tap share
* Select DDG
* Shows a blank address bar and the search says "Special Characters"

Note that the previous version didn't support sharing directly, but did work when you tried to "add people" to a note (and that still works).

**Comment by subsymbolic** [comment]
Thanks for the review @brindy. The predicate was based on Apple's documentation at https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW8

Regarding Notes that works for me, what was the text in your note?

**Comment by brindy** [comment]
No text, just a "Sketch" ... that's probably OK then.

**Pull request merged**
