### PR TITLE
Update embedded TDS

### PR DESCRIPTION
**Pull request by bwaresiak**
Task/Issue URL: https://app.asana.com/0/856498667320406/1201837636311069
Tech Design URL:
CC:

**Description**:
Update embedded TDS file, add tests and fix missing ETag when fetching config for the first time.

**Steps to test this PR**:

Test embedded list & etag.

Test configuration downloading and ETag usage.

General smoke tests.

**Device Testing**:

* [ ] iPhone 
* [ ] iPad

**OS Testing**:

* [ ] iOS 13
* [ ] iOS 14
* [ ] iOS 15

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Review by brindy — COMMENTED** [review]
Please update if needed and the re-assign to me.

**Comment by bwaresiak** [comment]
@brindy ready to look at!

**Comment by brindy** [comment]
I'm struggling to get the app to update the config.  Seems like it's not able to update tracker data or the bloom filter?  I've tried running as a background fetch and I've even done a clean install with the embedded etag and hash modified to make it look different.  Ping me when you're free and let's zoom it. :) 

Simulator Screen Shot - iPhone 13 Pro Max - 2022-04-20 at 13 48 55

**Comment by bwaresiak** [comment]
@brindy can this be a problem with debug screen? Maybe it doesn't show the embedded etag, but since it matches remote one nothing is stored?

**Review by brindy — APPROVED** [review]
My bad! I was looking at the wrong provider's ETag.  This is working just fine.

**Pull request merged**
