### PR TITLE
Onboarding intro - Browsers Comparison Chart

### PR DESCRIPTION
**Pull request by alessandroboron**
Task/Issue URL: https://app.asana.com/0/1206329551987282/1207641150516601/f
CC: @SabrinaTardio 

**Description**:
Implements the Browsers comparison chart to be embedded in DaxDialog in the Intro flow.

**Known Issues**
1. The safari Icon looks bigger than DDG Icon. Waiting for Shaun to reply to my [Figma comment](https://www.figma.com/design/WAuc7qCp0hPikEBcZuD99h?node-id=1-8656&m=dev#847718175)
2. Cross icon (unavailable state) background color renders differently than Figma design for Dark Mode. Waiting for Shaun to reply to my [Figma comment](https://www.figma.com/design/WAuc7qCp0hPikEBcZuD99h?node-id=1-9307&m=dev#849348120)  

**Steps to test this PR**:
1. Checkout the code and check SwiftUI Preview of:
   - DaxDialogBrowsersComparisonView 

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [x] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPhone 14 Pro
* [ ] iPad

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15
* [x] iOS 16

**Theme Testing**:

* [x] Light theme
* [x] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Review by brindy — APPROVED** [review]
Looks fine with the current text. I tried it on a bunch of different devices and it worked.  However, when I made some of the text extra long it truncated. I think it should flow on to the second line as might happen if translated.   Please check with design how it should look in that case (I'll add a comment in asana too).

**Comment by alessandroboron** [comment]
> Looks fine with the current text. I tried it on a bunch of different devices and it worked. However, when I made some of the text extra long it truncated. I think it should flow on to the second line as might happen if translated. Please check with design how it should look in that case (I'll add a comment in asana too).

Ah good catch, I checked with design and it should wrap on two lines. I will work on the fix.

**Comment by alessandroboron** [comment]
> Looks fine with the current text. I tried it on a bunch of different devices and it worked. However, when I made some of the text extra long it truncated. I think it should flow on to the second line as might happen if translated. Please check with design how it should look in that case (I'll add a comment in asana too).

@brindy I’ve refactored the View and Model. Now it’s much simpler and handle multi line text. Special thanks to @SabrinaTardio for helping simplyfing the view!

**Review by brindy — APPROVED** [review]
This doesn't work properly for me.  When using the preview with comparison embedded it is truncating text:

Screenshot 2024-06-26 at 13 24 37

I noticed that adding the following line fixes that though:

Screenshot 2024-06-26 at 13 25 38

ie 

`.fixedSize(horizontal: false, vertical: true)`

Can you add that and give it a bit of a test?  If it's OK, feel free to go ahead and merge.

**Comment by alessandroboron** [comment]
> This doesn't work properly for me. When using the preview with comparison embedded it is truncating text:
> Can you add that and give it a bit of a test? If it's OK, feel free to go ahead and merge.

For some reasons I had this one and I removed it before pushing. Thanks for checking I’ve added it and works as expected. Merging in.

**Pull request merged**
