### PR TITLE
Improve localization comments for VoiceOver labels

### PR DESCRIPTION
**Pull request by mallexxx**
Task/Issue URL: https://app.asana.com/0/414709148257752/1203344021820489/f
Smartling:
- [a Bookmark](https://dashboard.smartling.com/app/projects/bbfe7b3b7/strings/jobs/rxvl6ysoj4vy)
- [to Bookmark](https://dashboard.smartling.com/app/projects/bbfe7b3b7/strings/jobs/dyzddgfa28j3)
CC: @Bunn 

**Description**:
Improve several VoiceOver items ids and fix translation inconsistencies

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Comment by mallexxx** [comment]
@Bunn, I fixed some translations: used https://github.com/mozilla-mobile/firefox-ios as a source (Shared/xx.lproj/Localizable.strings:"HomePanel.ContextMenu.Bookmark"), can you give it another pass please?

**Review by joh805 — APPROVED** [review]

**Comment by mallexxx** [comment]
@Bunn, I‘ve updated the translations (see `alex-bookmark-fix-3` SL job) and const labels to better describe; 
This also includes the overlapping "Add (all open tabs) to Bookmarks" translation which had a wrong "a Bookmark" translation for some languages.

**Review by Bunn — APPROVED** [review]
LGTM.
2 questions:
1 - Do you have an asana task for this?
2 - Did you change the translations on smartlings as well or only on code?

Thanks

**Comment by mallexxx** [comment]
1> Should we use a new subtask in this? https://app.asana.com/0/72649045549333/1202621026047124/f
2> Yes, smartling translations are updated and verified new translations using the updated values

**Pull request merged**
