### PR TITLE
Add notes to autofill logins

### PR DESCRIPTION
**Pull request by THISISDINOSAUR**
Task/Issue URL: https://app.asana.com/0/0/1203021186566017/f, https://app.asana.com/0/0/1202809065048065/f
Tech Design URL:
CC:

**Description**:
Linked to this BSK PR: https://github.com/duckduckgo/BrowserServicesKit/pull/142
Updates BSK to include notes support, and changes the login management interface to have a notes field.

**Steps to test this PR**:
1. Edit an existing login to have notes
2. Create a new login with a note. 
3. Create a new login with a very long note, and check that the notes field eventually stops growing. The view should truncate, or if in edit mode should scroll.

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPad

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Comment by THISISDINOSAUR** [comment]
There is a bug when moving from view to edit with the notes field, the initial size is incorrect. I think for now I'm happy to leave it and possibly take a look later
https://user-images.githubusercontent.com/1093508/192007321-7f15112c-9c24-4365-8bdf-213b7bb4ee9c.mp4

**Review by amddg44 — COMMENTED** [review]
Everything worked perfectly including migration and creating super long notes 👍 

Just a couple of small UI issues:
- the copy confirmation message is wrong
        

- padding is off when in edit mode
        

As you flagged, the initial size is incorrect when moving from view to edit so ignoring that. It would be nice if notes scrolled up with the keyboard when selected, but I think that can also be left as a future enhancement.

**Comment by THISISDINOSAUR** [comment]
Good spot! I've fixed the copy. I fixed the vertical padding, but for the life of me haven't be able to fix the horizontal padding, it just never wants to be less. Not sure what's going on there.
Good point re scrolling, agree to leave for now though

**Review by amddg44 — APPROVED** [review]
No worries, the horizontal padding can be a future improvement. Otherwise LGTM!

**Pull request merged**
