### PR TITLE
delete bookmark favicon if currently deleted bookmark is the last one left

### PR DESCRIPTION
**Pull request by brindy**
Task/Issue URL:  https://app.asana.com/0/414235014887631/1204217694278073/f
Tech Design URL:
CC:

**Description**:

Ensures favicon for bookmark domain is deleted when that domain is now longer in the bookmarks database.

**Steps to test this PR**:
1. Add a bookmark for a domain
2. Check that favicon was saved to cache
3. Delete bookmark, ensure favicon was deleted
4. Add two bookmarks for the same domain (different URLs)
5. Check that one favicon was saved to cache
6. Delete one of the bookmarks, ensure the favicon is still in the cache
7. Delete the second bookmark, ensure the favicon is deleted

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPhone 14 Pro
* [ ] iPad

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15
* [ ] iOS 16

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Comment by amddg44** [comment]
Hey @brindy, nice catch on only deleting the favicon when it is the last one remaining for a domain!  I've flagged a couple of issues while testing:

1. If a bookmark has a `www.` prefix e.g. `www.nytimes.com` its favicon is not being deleted from the favicon cache
2. Deleting favorites from the new tab screen does not delete the favicon

**Comment by brindy** [comment]
Thanks @amddg44 

1/ I'll look at that, thanks.

2/ This is because the bookmark is not deleted, just the favorite flag is removed as per the new model.

**Comment by brindy** [comment]
@amddg44 I've removed the drop www prefix call when checking the domain.  Seems like most sites redirect to one or the other.  That should address your first point.  Thanks!

**Comment by amddg44** [comment]
@brindy nice, that change is working well! And thanks for clarifying the new behaviour arounds favorites; all looks good there too in that case 🙂 

I did spot another edge case during my latest round of testing - when deleting a folder of bookmarks, the favicons of the bookmarks within the folder are not deleted

**Comment by brindy** [comment]
Ugh, nice one! I'll fix that.

**Comment by brindy** [comment]
There you go @amddg44.  

I created the following structure for testing:

* Twitter
* Folder 1
    * CNN
    * Facebook
    * Twitter (different page)
    * Folder 2
        * Nike

Then deleted Folder 1 and it left behind the Twitter favicon as expected.
Then deleted Twitter from the root and it removed that too.

**Comment by amddg44** [comment]
Excellent, thanks! I'll test that now 👍

**Review by amddg44 — APPROVED** [review]
LGTM!

**Comment by brindy** [comment]
Thank you!

**Pull request merged**
