### PR TITLE
Fix Browsing Menu layout issues around longer copy

### PR DESCRIPTION
**Pull request by bwaresiak**
Task/Issue URL: https://app.asana.com/0/414709148257752/1203039305560249
Tech Design URL:
CC:

**Description**:

This fixes Browsing menu layout issues when copy is long. 

**Steps to test this PR**:

Test on iPhone and iPad + rotation.

**Orientation Testing**:

* [x] Portrait
* [x] Landscape

**Device Testing**:

* [x] iPhone 
* [x] iPad

**OS Testing**:

* [x] iOS 14
* [x] iOS 15
* [x] iOS 16

**Theme Testing**:

* [x] Light theme
* [x] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Comment by bwaresiak** [comment]
There is one corner case issue I've seen when transitioning from iPhone to iPad mode during rotation - height of menu remains "too big" It is not breaking anything so I just left that in.

**Review by amddg44 — APPROVED** [review]
I've tested iPhone & iPad in portrait & landscape across iOS 14, 15 and 16 in multiple languages and everything looks good!  

There is just one small visual issue on iPad iOS 14 where the height is always too big (even without rotating) but it does not affect functionality

<image src="https://user-images.githubusercontent.com/91189922/198571186-e61e5ee5-68ba-4a15-8813-9e1b884aa6c1.png" width=200><image src="https://user-images.githubusercontent.com/91189922/198571326-cefef94c-9b22-4eb8-9988-b206afbaf295.png" width=300>

**Comment by bwaresiak** [comment]
@amddg44 I *think* I've fixed that, can you re-check? Thanks!

**Comment by amddg44** [comment]
@bwaresiak I rechecked across all iOS versions + devices types and that fix did the trick, nice!

**Comment by bwaresiak** [comment]
Thanks @amddg44 !

**Pull request merged**
