### PR TITLE
Switch between Grid and List on TabSwitcher screen

### PR DESCRIPTION
**Pull request by bwaresiak**
Task/Issue URL: 
- https://app.asana.com/0/856498667320406/1182275725806795
- https://app.asana.com/0/856498667320406/1183105629066081

Tech Design URL:
CC:

**Description**:

Added an option to switch between Grid and List on TabSwitcher screen and fixed the problem when previews could disappear randomly.

**Steps to test this PR**:

**Tab switcher**

1. Open tab switcher.
2. Toggle between Grid and List views.

To check:
- Transition animation.
- Whether the setting is properly persisted.
- Basic functionality (removing tabs, reordering, swipe to delete).
- When list mode is enabled, new previews are not stored in the file system cache (old ones will be purged when given tab is removed or when app is restarted).
- General smoke tests.

**Previews improvements**

- Migration from previous version should work.
- Old previews location (Cache dir) should be purged.
- As old one, new location should not be backed up.
- Auto Clear functionality and tabs purging/removing should also remove previews.

**Orientation Testing**:

* [x] Portrait
* [x] Landscape

**Device Testing**:

* [x] iPhone SE (1st Gen)
* [x] iPhone 8
* [x] iPhone X
* [x] iPad

**OS Testing**:

* [x] iOS 10
* [x] iOS 11
* [x] iOS 12
* [x] iOS 13

**Theme Testing**:

* [x] Light theme
* [x] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Review by brindy — APPROVED** [review]
This makes my heart sing with joy!

**Review by brindy — APPROVED** [review]
LGTM!

**Review by brindy — APPROVED** [review]
smoke tested last pushes and LGTM

**Comment by bwaresiak** [comment]
Thank you!

**Pull request merged**
