### PR TITLE
Add build linting step for JavaScript

### PR DESCRIPTION
**Pull request by jonathanKingston**
Task/Issue URL: https://app.asana.com/0/0/1201333032847232/f
Tech Design URL:
CC:

**Description**:

@bwaresiak this is the discussed build step changes. As you can see we've been adding more changes that breaks ESLint and it's easier to wine up front to the engineer than have it on PR or releasing :)

**Steps to test this PR**:
1. Ensure project builds without errors

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Review by bwaresiak — COMMENTED** [review]
This fails for me with `command not found: npm` - most likely because PATH is not set correctly in the script.

Nonetheless I'm not sure we want to include setup (install) step as part of the build - it's not for the swiftlint so I'd keep that the same. 

I'm going to bring this up in the weekly meeting so we can wrap this up next week as it's been a wile since this has been opened.

**Comment by bwaresiak** [comment]
@jonathanKingston we've had a chat about this, and we would rather avoid changing dev environment in the build scripts - that should be part of the setup before the compilation that is part of the readme.

**Comment by jonathanKingston** [comment]
I'll rebase this and remove out the npm install in the build phase as part of quick wins.

**Comment by catehstn** [comment]
@jonathanKingston any update on this?

**Comment by jonathanKingston** [comment]
No, let's close this and retain the task in Asana. I don't have time to work on this.

**Pull request closed without merging**
