### PR TITLE
Fix for URL bar sometimes fails to select URL on tap 

### PR DESCRIPTION
**Pull request by amddg44**
Task/Issue URL: https://app.asana.com/0/414709148257752/1201408131067984/f
Tech Design URL:
CC:

**Description**:
Change to url selection behaviour so that cursor no longer moves to end of the url when address bar tapped, as this impacted the selection of the URL. 

**Steps to test this PR**:
1. Visit URLs with long and short addressed and confirm that when tapping the address bar the cursor does not move to the end of the address and that the full address is selected every time

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPhone 14 Pro
* [ ] iPad

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15
* [ ] iOS 16

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Review by brindy — COMMENTED** [review]
I think this fixes the problem of selection, but unfortunately it introduces other problems (which historically is why the code was the DispatchQueue mess that it was):

If you tap near the left you get this (the selection handle is off the edge):
Screenshot 2022-10-10 at 23 25 46

If you tap near the right you get this (the selection handles are missing):
Screenshot 2022-10-10 at 23 27 50

Any thoughts how to improve that?

**Review by brindy — APPROVED** [review]
I reached out to Gabe to see what he thinks and we agreed selecting is better than not even with those selection handle weirdness, so am approving this. :) 

Can you please create a follow up task to look at that another time?  

Thanks!

**Comment by brindy** [comment]
Created the follow up task since it was already in my brain :) 

https://app.asana.com/0/414709148257752/1203132885003287/f

**Comment by amddg44** [comment]
Thanks @brindy! Nice catch with the edge cases (literally!) + thanks for creating the follow up task 🙂

**Pull request merged**
