### PR TITLE
Autofill favicon caching change

### PR DESCRIPTION
**Pull request by amddg44**
Task/Issue URL: https://app.asana.com/0/0/1204139098882276/f
Tech Design URL:
CC:

**Description**:
Update to Autofill favicons to also use the fireproof cache, in line with Android

**Steps to test this PR**:
1. Launch the app and search for the `favicons fireproof location` from console (it's usually about the 7th line printed on launch) and go to the folder in Finder and delete all the favicons stored there (or make a note of those that are there)
2. Visit a website with a favicon e.g. netflix.com
3. Login and save the login when prompted
4. Visit the saved login and confirm the favicon is visible on the main logins list screen and also on the details screen for the login
5. Logout and confirm that when logging back in the favicon is shown on the autofill prompt
6. Check in Finder and confirm the favicon has been saved there
7. Tap the fire button in the app and force quit to clear all the cached tab favicons
8. Confirm the favicon is still visible in the logins list screen and the login details screen
9. Delete the Login and confirm in Finder that, after the toast confirming the deletion is gone, that the favicon has been deleted

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPhone 14 Pro
* [ ] iPad

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15
* [ ] iOS 16

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Review by THISISDINOSAUR — COMMENTED** [review]
Testing lgtm!
- I don't think we should combine this into the bookmarks cache without further modification. I can see it making sense them both being part of the same cache. I'm assuming we want the exact same persistence behaviour for both? But in that case I think we should at least rename the bookmarks cache. Is there any discussion in asana around this?
- They don't appear in the debug menu along with the other cached images, would it be hard to add them?

**Comment by amddg44** [comment]
We do indeed want the exact same persistence behaviour for both. I saw that fireproof domains is already also using the bookmarks cache so I was following the existing pattern but I agree though that the naming is getting confusing. I'll throw together a proposal to rename the .bookmarks cache

The debug menu... tbh I think it needs a complete overhaul (which I am happy to tackle separately) as it only reads from bookmarks db, and displays favicons for those bookmarks if they have one so it is not actually presenting everything that is in the favicons cache. I'll put together a proposal for that too, thanks!

**Comment by amddg44** [comment]
@THISISDINOSAUR  this is now updated with the new .fireproof favicon cache name changes 🙂

**Review by THISISDINOSAUR — APPROVED** [review]
LGTM!

**Pull request merged**
