### PR TITLE
Improve unit test for AtbAndVariantCleanup

### PR DESCRIPTION
**Pull request by mauriciomaniglia**
Task/Issue URL: https://app.asana.com/0/414235014887631/1204857106550924/f

GitHub Issue: https://github.com/duckduckgo/iOS/issues/1708

**Description**:

- Improve test coverage for `AtbAndVariantCleanup ` by also checking a scenario when Atb has a different variant.
- Improve the current unit test `testWhenVariantIsNotInCurrentExperimentThenVariantRemovedFromStorage` by making more explicit the params values that are been tested.

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [x] iPhone 14 Pro
* [ ] iPad

**OS Testing**:

* [x] iOS 14
* [ ] iOS 15
* [ ] iOS 16

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Review by samsymons — APPROVED** [review]
LGTM, thanks @mauriciomaniglia!

P.S., sorry it's taken so long to get back to you here. We're in the process of revamping our repo's issue and PR triage process, so this should improve soon.

**Comment by samsymons** [comment]
@mauriciomaniglia Would you be able to merge `develop` changes into this branch in order to kick GitHub Actions? Once that's done and this is green, I'll merge it.

**Comment by mauriciomaniglia** [comment]
> LGTM, thanks @mauriciomaniglia!
> 
> P.S., sorry it's taken so long to get back to you here. We're in the process of revamping our repo's issue and PR triage process, so this should improve soon.

No problem. Thanks for letting me know.

**Comment by mauriciomaniglia** [comment]
> @mauriciomaniglia Would you be able to merge `develop` changes into this branch in order to kick GitHub Actions? Once that's done and this is green, I'll merge it.

✅

**Pull request merged**
