### PR TITLE
implement contextual dialogs

### PR DESCRIPTION
**Pull request by SabrinaTardio**
Task/Issue URL: https://app.asana.com/0/1204186595873227/1207736729379245/f

**Description**: Implements the Dialog we will use in the contextual onboarding
cc. @alessandroboron 

**Steps to test this PR**:
1. Use the Preview of the following files: ContextualDaxDialog, ContextualOnboardingList, ContextualOnboardingDialogs
2. the latest represent the top level ones that will be displayed

**Definition of Done (Internal Only)**:

* [ ] Does this PR satisfy our [Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f)?

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPhone 14 Pro
* [ ] iPad

**OS Testing**:

* [ ] iOS 15
* [ ] iOS 16
* [ ] iOS 17

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by alessandroboron** [comment]
As per MM conversation, there’s an issue with the typing animation. The box grows as the typing goes. We can look at adapting AnimatableTypingText with AttributedString. Having said that I think we should finish the functionality first and look at animations later.

**Comment by SabrinaTardio** [comment]
> As per MM conversation, there’s an issue with the typing animation. The box grows as the typing goes. We can look at adapting AnimatableTypingText with AttributedString. Having said that I think we should finish the functionality first and look at animations later.

I should have fixed it! but have not used the existing stuff when can always see later if we want to combine them.

**Review by brindy — CHANGES_REQUESTED** [review]
Works well, but I agree with @alessandroboron we should use the AnimatableTextView if possible.  

Using the `typeToDisplay` to coordinate the appearance of items is good, but it's a confusing name.  

Can you please change this:

* Don't use Dispatch.main (this should always be a last resort tbh) ... please use a SwiftUI timer and call it something like `animationScheduler` ([see this example](https://www.hackingwithswift.com/quick-start/swiftui/how-to-use-a-timer-with-swiftui))

* Ideally use AnimationTextView if possible, this can just appear like any other view will automatically handle showing the text

And as we mentioned, couple of SwiftLint things to fix as well.

Thanks

**Comment by alessandroboron** [comment]
Good job adapting AnimatableTypingText, it works very well! 👏 

The views that show a list of suggestions need a VM, but we can add it in another PR when we have the provider ready.

On another note, there’s a conflict with the main feature branch `DaxDialogIntroView`. I removed this file `DaxDialogIntroView.swift`, so it shouldn’t be too bad to resolve it.

**Review by brindy — APPROVED** [review]
LGTM, very nice. Agree with @alessandroboron we need a view model though, but can follow up with that.

**Comment by SabrinaTardio** [comment]
> LGTM, very nice. Agree with @alessandroboron we need a view model though, but can follow up with that.

Yes, I agree too there will be a need for a view model but it didn’t make sense to add it now when it does not do anything yet

**Pull request merged**
