### PR TITLE
Fix autofill auto-disable for first time users

### PR DESCRIPTION
**Pull request by Bunn**
Task/Issue URL: https://app.asana.com/0/414709148257752/1202526099545584/f
CC: @GioSensation @THISISDINOSAUR 

**Description**:
Fix issue where autofill was being disable once the user denied the save modal 3x.
This should only happen if the user disables 3x in a row for a first time user.

**Steps to test this PR**:

1. on a brand new app installation go to a website like https://news.ycombinator.com/login
2. Fill username/password
3. Reject the autofill modal to save it
4. Do the above 4x
5. On the 4th time, no prompt should be displayed to the user
6. Check under settings/autofill if autofill is disabled, it should

------
1. on a brand new app installation go to a website like https://news.ycombinator.com/login
2. Fill username/password
3. Reject the autofill modal to save it
4. Repeat the above, but on step 3 save the password instead of rejecting
5. Repeat steps 1-3 3x more (not saving it)
6. Autofill should be always enabled and prompting to save 
7. Check under settings/autofill if autofill is enabled, it should

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Comment by THISISDINOSAUR** [comment]
For some reason my attempt at saving a screen recording resulted in an empty file, but I had an issue
The actual bug this PR addresses seemed to be fixed, but then I was testing the case where I never save anything and was still prompted every time. I did deliberately test with dismissing the prompt in different ways (the button, the x, tapping above it), which might be the cause? I can't remember if that's deliberate behaviour?

Also unrelated, a lot of the time when I pressed submit on katesclothing.co.uk, the prompt comes up, but the form didn't submit. I never used to have this issue

**Comment by GioSensation** [comment]
> Also unrelated, a lot of the time when I pressed submit on katesclothing.co.uk, the prompt comes up, but the form didn't submit. I never used to have this issue

I can reproduce this. I'm trying to track it down.

**Comment by Bunn** [comment]
@THISISDINOSAUR ` I was testing the case where I never save anything and was still prompted every time`
Just to confirm, was this from a brand new installation? Because if it was saved even once, it will never turn it off again.

**Comment by THISISDINOSAUR** [comment]
> @THISISDINOSAUR ` I was testing the case where I never save anything and was still prompted every time`
> Just to confirm, was this from a brand new installation? Because if it was saved even once, it will never turn it off again.

Yeah, went through dad onboarding and everything, and saw the onboarding ui for autofill every time

**Comment by Bunn** [comment]
The issue happens if the user dismiss the modal by tapping outside instead of "not now" or "X" button.
I'll move the conversation if this is a desired effect to [Asana](https://app.asana.com/0/414709148257752/1202526099545584/f)

**Comment by Bunn** [comment]
On the [Asana task](https://app.asana.com/0/414235014887631/1202526099545584/f) it was decided that the way it's implemented in this PR is correct. i.e: ignoring the taps from outside the window when accounting for the dismissals.

**Comment by Bunn** [comment]
Closing this PR since this behavior might change once the [autofill design changes](https://app.asana.com/0/715106103902962/1202556489884417) are done

**Pull request closed without merging**
