### PR TITLE
Smoother new tab experience

### PR DESCRIPTION
**Pull request by romanrudyy**
Task/Issue URL: #915, https://app.asana.com/0/392891325557410/1200541656968208
Tech Design URL:
CC:

**Description**:

Please see #915 for description. Please check 278b756 regarding `viewed` property logic.

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [x] Portrait
* [x] Landscape

**Device Testing**:

* [x] iPhone SE (1st Gen)
* [x] iPhone 8
* [x] iPhone X
* [x] iPad

**OS Testing**:

* [x] iOS 13
* [x] iOS 14

**Theme Testing**:

* [x] Light theme
* [x] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Comment by samsymons** [comment]
@romanrudyy Thanks so much for opening this PR, I'm aiming to review this within the next few days. Thanks for the patience!

**Comment by romanrudyy** [comment]
Hey @samsymons , awesome! Things can be tweaked and changed, so yeah please let me how this looks. 
The biggest change apart from visuals is the `viewed` property usage. I made it `false` by default as IMO it is more correct. But obviously I may be wrong or I might have missed something,  looking forward to feedback.

**Comment by samsymons** [comment]
I'm still working on this one, it's been a busy week - I have time set aside to finish my review on Wednesday. Thanks again! 🙂

**Review by samsymons — APPROVED** [review]
Thanks for this @romanrudyy, I've run this a fair bit on a number of devices and everything looks to be working well - plus this is a nice visual improvement. 🙂 

Code looks good too, nice work!

**Comment by romanrudyy** [comment]
@samsymons Pleased to hear that! Thanks!

**Pull request merged**
