### PR TITLE
Bitwarden Integration

### PR DESCRIPTION
**Pull request by tomasstrba**
Task/Issue URL: https://app.asana.com/0/72649045549333/1202684343604567/f
Tech Design URL: https://app.asana.com/0/481882893211075/1202715202076385/f
https://app.asana.com/0/481882893211075/1202870974810231/f
CC: @samsymons

**Description**:
This PR brings BSK changes necessary for Bitwarden integration into macOS app and verifies iOS app is not influenced by the integration at all.

**Steps to test this PR**:
1. Test autofill, saving credentials and updating credentials
2. Make sure there is no issue related to autofill caused by BSK changes

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15
* [ ] iOS 16

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Review by samsymons — APPROVED** [review]
LGTM, have validated that Autofill is working as expected and tested other features around the edges.

**Comment by jdhauck** [comment]
I've been running into issues with the Bitwarden/DDG integration on macOS and was wondering is here the right place to raise them?

**Comment by samsymons** [comment]
Hey @jdhauck! Thanks for bringing this up. The easiest way to deliver feedback to the macOS team is to use the feedback form in the app - you can find this by clicking the "..." button and selecting "Send Feedback".

CleanShot 2023-05-28 at 17 41 08@2x

**Comment by jdhauck** [comment]
Hi @samsymons. Thank you, I  just submitted them through the feedback button. It seems there is no way to follow up with that though, or is there?  
Fwiw, I have thus also created a reddit post:    https://www.reddit.com/r/duckduckgo/comments/13v64gu/duckduckgobitwarden_integration_problems_in_ddg/ 

Keep up the good work :)

**Pull request merged**
