### PR TITLE
Remove temporary pixel for Subscription Progress Indicator

### PR DESCRIPTION
**Pull request by afterxleep**
Task/Issue URL:  https://app.asana.com/0/414235014887631/1207008719518535/f
Tech Design URL:
CC:

**Description**:
Removes temporary pixel

**Steps to test this PR**:
1.  CI should be 🥬 

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by Bunn** [comment]
> **Steps to test this PR**:
> 
>     1. CI should be 🥬

image

XD

**Comment by afterxleep** [comment]
😡 

It's now 🥬 @Bunn

**Review by Bunn — APPROVED** [review]
LGTM, just make sure to deal with the conflict :)

**Comment by afterxleep** [comment]
> LGTM, just make sure to deal with the conflict :)

Wish I didn't have to 👹

**Pull request merged**
