### PR TITLE
long press preview setting

### PR DESCRIPTION
**Pull request by brindy**
Task/Issue URL: https://app.asana.com/0/414235014887631/1145895736139511
Tech Design URL: 
CC:

**Description**:

Allows user to disable long press previews on links (not images since that's iOS)

**Steps to test this PR**:
1. Visit a site with links, preview should be shown for long press
1. Go to settings and change toggle for "Long-Press Links" to off
1. Visit a site with links, preview should not be shown for long press
1. Go to settings and change toggle for "Long-Press Links" to on
1. Visit a site with links, preview should be shown for long press
1. Ensure pixels fire for the different states

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Review by bwaresiak — CHANGES_REQUESTED** [review]
Two things:
- Toggling 'Long Press previews' also toggles 'Open link in associated apps' option - storyboard invokes more than one IBAction. 😃 
- Shouldn't this option be hidden for iOS <13 since it's useless there?

**Comment by brindy** [comment]
Thanks @bwaresiak - have updated with fixes.

**Review by bwaresiak — APPROVED** [review]
LGTM!

**Comment by brindy** [comment]
thanks!

**Pull request merged**
