### PR TITLE
Fix UI/Snapshot Tests

### PR DESCRIPTION
**Pull request by albsala**
Task/Issue URL: #559 
Tech Design URL: N/A
CC: N/A

**Description**:
UI/Snapshot tests are broken in develop branch so I fixed them up. It was just adding a couple of accesibilityIdentifiers and a couple of lines in UITests.swift.

**Steps to test this PR**:
1. Make `~/Library/Caches/tools.fastlane/screenshots/` folder
2. Select UITests Schema and test.

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by bwaresiak** [comment]
Hello @albsala 

Thanks for looking at this. I've checked out your branch and while it correctly goes through onboarding & add to home row dialog, it still fails for me after a while (after first set of screenshots is made).

`Failed to synthesize event: Neither element nor any descendant has keyboard focus. Event dispatch snapshot: SearchField, identifier: 'searchEntry', placeholderValue: 'Search or enter address', `

Note, that I've removed the app before running the test. Does this test pass for you?

**Comment by bwaresiak** [comment]
@albsala actually, please wait a bit before spending more time on this. :)

It looks like we are not using these tests anymore, so I'm going to discuss whether we should remove these instead.

Thanks!

Internal reference: https://app.asana.com/0/856498667320406/1158699016458265

**Comment by albsala** [comment]
@bwaresiak Tests were successful for me before sending the PR. Since it's a keyboard issue, it might be dependant on the simulator/settings we're using.
These tests were not been used in CI but I would suggest you to maintain them because they're pretty useful :)
Cheers

**Comment by bwaresiak** [comment]
@albsala We've had a chat about that and agreed that these tests are not really used anymore. Because of that, we'd like to avoid the cost of maintaining them and would prefer to remove these.

I'm specifically talking about:
- UI/Snapshot tests.
- IntegrationTests (do not confuse with AtbIntegration tests).
- TopSitesReport.

Instead of this PR, would you be willing to create one focused on removing all of the above? Thanks!

**Pull request closed without merging**
