### PR TITLE
Update BSK with autofill 10.2.0

### PR DESCRIPTION
**Pull request by daxmobile**
Task/Issue URL: https://app.asana.com/0/1206839421155398/1206839421155398
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.2.0
BSK PR: https://github.com/duckduckgo/BrowserServicesKit/pull/723

## Description
Updates Autofill to version [10.2.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/10.2.0).

## What's Changed
* Remove unused Android UA check by @jonathanKingston in https://github.com/duckduckgo/duckduckgo-autofill/pull/494
* fix tracker radar kit reference by @brindy in https://github.com/duckduckgo/duckduckgo-autofill/pull/505
* Update password-related json files (2024-03-04) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/518
* separate 'third party provider' feature by @shakyShane in https://github.com/duckduckgo/duckduckgo-autofill/pull/252
* marking flaky tests by @shakyShane in https://github.com/duckduckgo/duckduckgo-autofill/pull/524
* remove device-specifc 'isEnabled' checks by @shakyShane in https://github.com/duckduckgo/duckduckgo-autofill/pull/523
* fixing some flaky tests by @shakyShane in https://github.com/duckduckgo/duckduckgo-autofill/pull/526
* Fixes bugs for Lufthansa, Twitter, Rumble by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/529
* Update Github action dependency by @GioSensation in https://github.com/duckduckgo/duckduckgo-autofill/pull/531

## New Contributors
* @brindy made their first contribution in https://github.com/duckduckgo/duckduckgo-autofill/pull/505

**Full Changelog**: https://github.com/duckduckgo/duckduckgo-autofill/compare/10.1.0...10.2.0

## Steps to test
This release has been tested during autofill development. For smoke test steps see [this task](https://app.asana.com/0/1198964220583541/1200583647142330/f).

### CODE REVIEW

**Comment by amddg44** [comment]
@GioSensation @shakyShane it looks like there is an issue with this autofill release and email incontext signup on iOS. EmailManager.autofillUserScriptDidCompleteInContextSignup is no longer firing, so the final stage of the email sign-up and sign-in flows are broken with the Email Protection screen never getting dismissed. 

I checked and there were no errors in the console, it's like a message handler just stopped firing or was possibly removed? Let me know if I can do anything to help


https://github.com/duckduckgo/iOS/assets/91189922/4e0b6ea6-728d-43fb-9f42-fc18cf830893

https://github.com/duckduckgo/iOS/assets/91189922/a05f4e5a-3f00-4c57-ad01-4ab42e0d4891

**Comment by GioSensation** [comment]
FYI, we've noticed that the native side is not sending the proper `getRuntimeConfiguration` in the in-context signup webview. The [PR where we removed `isEnabled` checks](https://github.com/duckduckgo/duckduckgo-autofill/pull/523/files#diff-39cb8c42a25de5dce09b5fc0aacf6aca587b22abc2de6a9c985a36f9f6b9242d) is probably relying on the runtime config being present and correct, and this may cause the communication to start failing. Anya will look into this.

**Comment by amddg44** [comment]
Thanks both! The issue was indeed a runtime config support issue in the in-context webview; i've opened a [PR](https://github.com/duckduckgo/iOS/pull/2621) with a fix (and I also added a debug option to reset the days since installed to 0 for ease of testing the incontext signup flow) 
image

**Comment by GioSensation** [comment]
Nice! Thanks, Anya! FWIW, this is the options we have for email protection on Android, in case you need further inspiration.
CleanShot 2024-03-21 at 12 13 54

**Comment by amddg44** [comment]
Thanks @GioSensation that is definitely inspiring! 😄

**Review by amddg44 — APPROVED** [review]

**Pull request merged**
