### PR TITLE
support javascript opening and closing of windows

### PR DESCRIPTION
**Pull request by brindy**
Task/Issue URL: https://app.asana.com/0/392891325557410/1150230163112681
Tech Design URL:
CC:

**Description**:

Allows JS to open and close new windows.  

**Steps to test this PR**:

1. Make a donation to ProtonMail.  Note they are blocking us from using PayPal so hack the user agent to be Safari when you test - see attached patch.

1.  Sign in to ProtonMail.  Click upgrade, choose an annual fee, select PayPal.  Login to PayPal but don't complete the transaction.  Close the tab.  The ProtonMail tab detects the tab has closed.

1. Visit https://falkirkrpg.org.uk/noxwall/openlater.html - wait 10+ seconds.  No new tab should appear.  Click the button a new tab should appear.  Click the close button and the tab should close.

1. Open a new tab and go directly to https://falkirkrpg.org.uk/noxwall/close.html - the close button should appear to do nothing.

1. Open a new tab and go to https://falkirkrpg.org.uk/noxwall/open.html - click the open button, a new tab should appear.  Clicking the close button should close the tab.

1. Open a new tab and go to https://falkirkrpg.org.uk/noxwall/open.html - click the link, a new tab should appear.  Clicking the close button should close the tab.

Exploratory testing as usual.

[safari-useragent.diff.txt](https://github.com/duckduckgo/iOS/files/4192895/safari-useragent.diff.txt)

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Review by bwaresiak — APPROVED** [review]
Great job! I haven't been able to break anything :)

**Comment by bwaresiak** [comment]
@brindy There is one thing I've noticed when testing tabs:
1. Open https://falkirkrpg.org.uk/noxwall/open.html
2. Open another tab e.g. search.
3. Move back to first tab, select 'open' so new tab is created (as expected).

Problem: new tab is created at the end of the tabs list, so when it is closed, we get moved to search instead of source page.

**Review by bwaresiak — APPROVED** [review]
LGTM! :)

**Comment by brindy** [comment]
Thanks @bwaresiak  :)

**Pull request merged**
