### PR TITLE
MacOS Changes for Email Protection management

### PR DESCRIPTION
**Pull request by afterxleep**
Task/Issue URL: https://app.asana.com/0/72649045549333/1204615490114675/f
BSK PR: https://github.com/duckduckgo/BrowserServicesKit/pull/396

**Description**:
This includes BSK changes to support private email protection management and also streamlines the logic for password saving and update dialogs.   (Minor change on iOS required)

**Steps to test this PR**:
1. Smoke test password generation
2. Smoke test credential saving/updating prompt

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by amddg44** [comment]
@afterxleep I've thoroughly tested and have found just one flow that isn't quite working correctly - when selecting and then replacing a generated password. Steps to reproduce:
- Select a generated password
- Confirm the partial login has saved in Logins
- Modify the password to something else
- Enter a username
- Tap Save and should get the Save Login prompt
- Tap "Not Now"
- There should be no logins saved, but the partial login is still there

**Comment by afterxleep** [comment]
> @afterxleep I've thoroughly tested and have found just one flow that isn't quite working correctly - when selecting and then replacing a generated password. 

@amddg44.  While this might be "useful" this involves deleting user data.   Should we be deleting automatically saved logins if the user says no?   Is that part of the original scope of autofill?   

I'm trying to avoid unneeded/edge case logic from here.

**Comment by amddg44** [comment]
> > @afterxleep I've thoroughly tested and have found just one flow that isn't quite working correctly - when selecting and then replacing a generated password.
> 
> @amddg44. While this might be "useful" this involves deleting user data. Should we be deleting automatically saved logins if the user says no? Is that part of the original scope of autofill?
> 
> I'm trying to avoid unneeded/edge case logic from here.

@afterxleep sure, understood but this is the agreed spec so am testing based on this https://app.asana.com/0/0/1204477250680453/f

**Comment by afterxleep** [comment]
@amddg44 Given the purpose of partial logins is to protect users from our flaky JS form submission detection, I've updated this, so partial logins are cleaned up when we detect a form submission.  (This covers your test scenario where multiple logins were created)

See update in BSK [here](https://github.com/duckduckgo/BrowserServicesKit/pull/396/commits/9c257db633987b5d0dc5414179f4f074ef1690ce)

**Comment by afterxleep** [comment]
Closing this PR as iOS now supports Email management via https://github.com/duckduckgo/iOS/pull/1828

**Pull request closed without merging**
