### PR TITLE
Autofill Settings layout improvements for landscape / iPad

### PR DESCRIPTION
**Pull request by amddg44**
Task/Issue URL: https://app.asana.com/0/72649045549333/1202809065048067/f
Tech Design URL:
CC:

**Description**:
Landscape and iPad layout handling for all screens associated with Autofill Settings including: 
- locked view
- empty autofill view (enabled and disabled states) 
- list view with items and 
- empty search results

**Steps to test this PR**:
1. Run through the different view states confirming the layouts match designs for iPhone landscape and iPad portrait & landscape
2. Confirm iPhone portrait layouts are still correct

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPad

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

### CODE REVIEW

**Comment by THISISDINOSAUR** [comment]
Still looking at if, but encountered a couple of issues, 1st is no edit button (iPhone 14, iOS 16)
Simulator Screen Shot - iPhone 14 - 2022-10-03 at 18 13 36

And on the same device, I'm encountering a break point when attempting to view an individual login
Screenshot 2022-10-03 at 18 14 53

**Comment by amddg44** [comment]
> Still looking at if, but encountered a couple of issues, 1st is no edit button (iPhone 14, iOS 16) 

Ok, this is one is because Autofill was disabled. I reviewed the designs and confirmed that if Autofill is disabled but user has saved logins there should be an Edit button and have made this change

**Comment by amddg44** [comment]
> And on the same device, I'm encountering a break point when attempting to view an individual login

This one is strange and I cannot reproduce on my side at all - is this happening for you with all devices? Wondering if it could be a conflict with a previous build that perhaps had notes saved?

**Comment by THISISDINOSAUR** [comment]
Ah I didn't notice autofill was disabled, the sooner we fix the disabling logic there the better! (I'm working on it atm)
That's a good shout, it's almost certainly because of notes

**Comment by THISISDINOSAUR** [comment]
Oh actually I have been able to replicate the breakpoint on a new device

Screenshot 2022-10-04 at 11 55 42

**Comment by THISISDINOSAUR** [comment]
The search bar and section index are different to design, but my bad on the section index for not spotting that the designs aren't platform idiomatic, so don't think we should change it.
The search bar though I'm not sure about. ATM it's the same as in bookmarks, but I looked around a bit for what other apps do and music has a search bar like we have on smaller devices, but it was the only one I could find. WDYT?

Simulator Screen Shot - iPad Air (5th generation) - 2022-10-04 at 11 53 44

**Comment by THISISDINOSAUR** [comment]
I tried doing a clean build and now the it's gone 🤷‍♀️

**Comment by Chaudhary24-cyber** [comment]
> Task/Issue URL: https://app.asana.com/0/72649045549333/1202809065048067/f Tech Design URL: CC:
> 
> **Description**: Landscape and iPad layout handling for all screens associated with Autofill Settings including:
> 
> * locked view
> * empty autofill view (enabled and disabled states)
> * list view with items and
> * empty search results
> 
> **Steps to test this PR**:
> 
> 1. Run through the different view states confirming the layouts match designs for iPhone landscape and iPad portrait & landscape
> 2. Confirm iPhone portrait layouts are still correct
> 
> **Copy Testing**:
> 
> * [ ]  Use of correct apostrophes in new copy, ie `’` rather than `'`
> 
> **Orientation Testing**:
> 
> * [ ]  Portrait
> * [ ]  Landscape
> 
> **Device Testing**:
> 
> * [ ]  iPhone SE (1st Gen)
> * [ ]  iPhone 8
> * [ ]  iPhone X
> * [ ]  iPad
> 
> **OS Testing**:
> 
> * [ ]  iOS 14
> * [ ]  iOS 15
> 
> **Theme Testing**:
> 
> * [ ]  Light theme
> * [ ]  Dark theme
> 
> ###### Internal references:
> [Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552) [Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943) **When ready for review, remember to post the PR in MM**

**Comment by apalud44** [comment]
> The search bar though I'm not sure about. ATM it's the same as in bookmarks, but I looked around a bit for what other apps do and music has a search bar like we have on smaller devices, but it was the only one I could find. WDYT?

Yeah, I go back and forth on this. ATM I'm leaning towards default iOS 16 behaviours and kicking off a conversation on this with design, but don't have a strong opinion either way

**Comment by amddg44** [comment]
> The search bar though I'm not sure about. ATM it's the same as in bookmarks, but I looked around a bit for what other apps do and music has a search bar like we have on smaller devices, but it was the only one I could find. WDYT?

Yeah, I go back and forth on this. ATM I'm leaning towards default iOS 16 behaviours and kicking off a conversation on this with design, but don't have a strong opinion either way

**Comment by THISISDINOSAUR** [comment]
> > The search bar though I'm not sure about. ATM it's the same as in bookmarks, but I looked around a bit for what other apps do and music has a search bar like we have on smaller devices, but it was the only one I could find. WDYT?
> 
> Yeah, I go back and forth on this. ATM I'm leaning towards default iOS 16 behaviours and kicking off a conversation on this with design, but don't have a strong opinion either way

Yeah, that sounds good to me.

Either way, code looks good to me, so I don't see any reason to not merge this if you'd rather before that convo is concluded

**Review by THISISDINOSAUR — APPROVED** [review]

**Pull request merged**
